# ruff: noqa: E501
"""Fail-closed manuscript output from the validated HARTH result schema."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[3]
sys.path.insert(0, str(REPO / "src"))
from howhow.episodes.harth.v2.result_schema import ResultSchemaError, validate_result  # noqa: E402

OUTPUT = ROOT / "generated" / "results.tex"
PLACEHOLDER = r"""% Generated by tools/generate_tables.py. Do not edit.
\section{Results Placeholder}
\begin{table}[ht]
\label{tab:results-folds}
\centering
\fbox{\parbox{0.82\linewidth}{\centering\Large UNVERIFIED\\[4pt]\normalsize No validator-approved v2 result artifact was supplied.\\Metrics are intentionally withheld.}}
\end{table}
"""


def validated(data: object) -> bool:
    try:
        validate_result(data)
        return True
    except (ResultSchemaError, TypeError):
        return False


def latex(data: dict[str, object]) -> str:
    result = validate_result(data)
    analysis = result["analysis"]
    rows = []
    for fold in result["folds"]:
        state = fold["states"]["calibrated"]
        metrics = state["metrics"]
        uncertainty = state["uncertainty"]
        rows.append(
            f"{fold['fold_id']} & {metrics['nll']:.6f} & {uncertainty['nll'][0]:.6f}--"
            f"{uncertainty['nll'][1]:.6f} & {metrics['brier']:.6f} & {metrics['ece']:.6f} "
            r"\\"
        )
    calibration_rows = []
    for metric, p_value in analysis["primary_calibration"]["adjusted_p"].items():
        calibration_rows.append(f"{metric} & {p_value:.6f} \\ ")
    ablation_rows = []
    for key, p_value in analysis["exploratory_ablation"]["adjusted_p"].items():
        ablation_rows.append(f"{key} & {p_value:.6f} \\ ")
    support_rows = []
    diagnostics = analysis["diagnostics"]
    for key, count in diagnostics["window_counts"].items():
        support_rows.append(f"{key} & {count} \\ ")
    failure_rows = [f"{failure} \\ " for failure in diagnostics["failures"]] or ["none \\ "]
    return (
        "% Generated by tools/generate_tables.py. Do not edit.\n"
        "Values below are copied only after strict schema validation; no metric is hand-entered.\n"
        "\\section{Validated Protocol-v2 Results}\n"
        "\\begin{table}[ht]\n\\centering\n"
        "\\caption{Calibrated fold metrics and named NLL uncertainty intervals.}\n"
        "\\label{tab:results-folds}\n"
        "\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Fold & NLL & NLL 95\\% interval & Brier & ECE \\\\\n\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
        "\\begin{table}[ht]\n\\centering\n\\caption{Paired calibrated versus uncalibrated bootstrap comparisons.}\n"
        "\\label{tab:results-calibration}\n\\begin{tabular}{lr}\n\\toprule\nMetric & Holm adjusted p \\\\\n\\midrule\n"
        + "\n".join(calibration_rows)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
        "\\begin{table}[ht]\n\\centering\n\\caption{Sensor ablation comparisons.}\n"
        "\\label{tab:results-ablations}\n\\begin{tabular}{lr}\n\\toprule\nComparison & Holm adjusted p \\\\\n\\midrule\n"
        + "\n".join(ablation_rows)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
        "\\begin{table}[ht]\n\\centering\n\\caption{Window support and preserved failures.}\n"
        "\\label{tab:results-diagnostics}\n\\begin{tabular}{lr}\n\\toprule\nPopulation & Windows \\\\\n\\midrule\n"
        + "\n".join(support_rows)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
        "\\paragraph{Preserved failures.}\n\\begin{verbatim}\n"
        + "\n".join(failure_rows)
        + "\\end{verbatim}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, default=ROOT / "artifacts" / "results-v2.json")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    try:
        data = (
            json.loads(args.artifact.read_text(encoding="utf-8"))
            if args.artifact.is_file()
            else None
        )
    except (OSError, json.JSONDecodeError):
        data = None
    content = latex(data) if isinstance(data, dict) and validated(data) else PLACEHOLDER
    if args.check_only:
        return int(not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content)
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
