# ruff: noqa: E501
"""Generate manuscript tables/figures from a validated protocol-v2 result artifact.

Missing or invalid artifacts deliberately produce the redacted placeholder. This tool
never fabricates metrics and never accepts a hand-entered metric override.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "results.tex"
PLACEHOLDER = r"""% Generated by tools/generate_tables.py. Do not edit.
\section{Results Placeholder}
\begin{table}[ht]
\centering
\caption{Protocol-v2 metrics.}
\label{tab:results}
\fbox{\parbox{0.82\linewidth}{\centering\Large UNVERIFIED\\[4pt]\normalsize No validator-approved v2 result artifact was supplied.\\Metrics are intentionally withheld.}}
\end{table}
\begin{figure}[ht]
\centering
\fbox{\parbox{0.72\linewidth}{\centering\Large UNVERIFIED\\[4pt]\normalsize Figure generation is closed until validated fold-level artifacts exist.}}
\caption{Protocol-v2 result figure placeholder.}
\label{fig:results}
\end{figure}
"""


def validated(data: object) -> bool:
    if not isinstance(data, dict) or data.get("schema_version") != "v2":
        return False
    if data.get("status") != "VALIDATED" or data.get("protocol_version") != "protocol-v2":
        return False
    gates = data.get("gates")
    required = {"provenance", "frozen_split", "leakage", "finite_metrics", "class_coverage"}
    if not isinstance(gates, dict) or required - set(gates) or not all(gates.values()):
        return False
    folds = data.get("folds")
    if not isinstance(folds, list) or not folds:
        return False
    for fold in folds:
        if not isinstance(fold, dict) or not isinstance(fold.get("subject"), str):
            return False
        metrics = fold.get("metrics")
        if not isinstance(metrics, dict) or not all(
            isinstance(metrics.get(name), int | float) for name in ("nll", "brier", "ece")
        ):
            return False
    return True


def latex(data: dict[str, object]) -> str:
    folds = data["folds"]
    assert isinstance(folds, list)
    rows = []
    for fold in folds:
        assert isinstance(fold, dict)
        metrics = fold["metrics"]
        assert isinstance(metrics, dict)
        rows.append(
            f"{fold['subject']} & {metrics['nll']:.6f} & {metrics['brier']:.6f} & {metrics['ece']:.6f} \\\\"
        )
    return (
        """% Generated by tools/generate_tables.py. Do not edit.
\\section{Results}
The following values are copied mechanically from the validator-approved protocol-v2 artifact; no metric is hand-entered in the manuscript.
\\begin{table}[ht]
\\centering
\\caption{Outer-fold metrics from the validated protocol-v2 artifact.}
\\label{tab:results}
\\begin{tabular}{lrrr}
\\toprule
Test subject & NLL & Brier & ECE \\\\
\\midrule
"""
        + "\n".join(rows)
        + """
\\bottomrule
\\end{tabular}
\\end{table}
\\begin{figure}[ht]
\\centering
\\fbox{\\parbox{0.72\\linewidth}{\\centering Validated fold-level artifact supplied; plotting remains a deterministic future step.}}
\\caption{Validated-result figure slot; no visual metric is inferred here.}
\\label{fig:results}
\\end{figure}
"""
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, default=ROOT / "artifacts" / "results-v2.json")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.artifact.is_file():
        content = PLACEHOLDER
    else:
        try:
            data = json.loads(args.artifact.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            data = None
        content = latex(data) if validated(data) else PLACEHOLDER
    if args.check_only:
        expected = content
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        return 0 if actual == expected else 1
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
