# ruff: noqa: E501
"""Fail-closed manuscript output from the validated HARTH result schema."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[3]
sys.path.insert(0, str(REPO / "src"))
from howhow.episodes.harth.v2.result_schema import ResultSchemaError, validate_result  # noqa: E402

OUTPUT = ROOT / "generated" / "results.tex"
PLACEHOLDER = r"""% Generated by tools/generate_tables.py. Do not edit.
\section{Results Placeholder}
\begin{table}[ht]
\centering
\fbox{\parbox{0.82\linewidth}{\centering\Large UNVERIFIED\\[4pt]\normalsize No validator-approved v2 result artifact was supplied.\\Metrics are intentionally withheld.}}
\end{table}
\begin{figure}[ht]
\centering
\fbox{\parbox{0.72\linewidth}{\centering\Large UNVERIFIED\\[4pt]\normalsize Calibrated-vs-uncalibrated uncertainty, sensor ablations, class support, and diagnostics are closed until a validated artifact exists.}}
\caption{Protocol-v2 result figure placeholder.}
\label{fig:results}
\end{figure}
"""


def validated(data: object) -> bool:
    try:
        validate_result(data)
        return True
    except (ResultSchemaError, TypeError):
        return False


def latex(data: dict[str, object]) -> str:
    result = validate_result(data)
    rows = []
    for fold in result["folds"]:
        state = fold["states"]["calibrated"]
        metrics = state["metrics"]
        rows.append(f"{fold['fold_id']} & {metrics['nll']:.6f} & {metrics['brier']:.6f} & {metrics['ece']:.6f} " + "\\\\")
    return """% Generated by tools/generate_tables.py. Do not edit.
\\section{Results}
Values below are mechanically copied from the validator-approved schema artifact; no metric is hand-entered.
\\begin{table}[ht]
\\centering
\\caption{Calibrated outer-fold metrics.}
\\label{tab:results}
\\begin{tabular}{lrrr}
\\toprule
Fold & NLL & Brier & ECE \\\\
\\midrule
""" + "\n".join(rows) + r"""
\\bottomrule
\\end{tabular}
\\end{table}
\\begin{figure}[ht]
\\centering
\\fbox{\\parbox{0.78\\linewidth}{\\centering Validated artifact: paired uncertainty, full/back/thigh ablations, class support, and optimizer diagnostics are available to downstream plotting.}}
\\caption{Predefined protocol-v2 diagnostic figure slot.}
\\label{fig:results}
\\end{figure}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, default=ROOT / "artifacts" / "results-v2.json")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    try:
        data = json.loads(args.artifact.read_text(encoding="utf-8")) if args.artifact.is_file() else None
    except (OSError, json.JSONDecodeError):
        data = None
    content = latex(data) if isinstance(data, dict) and validated(data) else PLACEHOLDER
    if args.check_only:
        return int(not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content)
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
